### ISSUE TITLE
Bug: function deployment outputs error

### ISSUE THREAD

**Issue by anatoliyfedorenko** [triggermesh/knative-lambda-runtime#20] opened 2019-01-15 10:10 UTC
Tried to deploy functions with NodeJS and Go, after a lot of waiting, it outputs the following lines:
`ERROR: logging before flag.Parse: E0115 15:54:14.201737   27783 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 123; INTERNAL_ERROR`

Then I quit, but after all found out that the function indeed works, just need to wait some more time. Need to understand where it comes from and how to avoid that error.

**Comment by tzununbekov** [comment] 2019-01-15 10:20
Duplicates #1

**Comment by tzununbekov** [comment] 2019-01-15 10:25
@anatoliyfedorenko what version of `tm` are you using?

**Comment by sebgoa** [comment] 2019-01-15 10:43
I think it is an issue with pushing to the registry

**Comment by sebgoa** [comment] 2019-01-16 07:39
LEt's close as duplicate of #1

**Closed as completed by sebgoa** 2019-01-16 07:39 UTC
